---
- name: Install awx-cli
  shell: 'pip3 install "https://github.com/ansible/awx/archive/9.2.0.tar.gz#egg=awxkit&subdirectory=awxkit"'
  when: "'hap1' in inventory_hostname"

- name: Wait until DB is migrating
  shell: /usr/local/bin/awx --conf.username admin --conf.password password --conf.host http://192.168.10.10 instance_groups list -f human
  when: "'hap1' in inventory_hostname"
  retries: 99
  delay: 10
  register: result
  until: result.rc == 0 and result.stdout != 'IsMigrating'

- name: Wait untill instance group is created
  shell: /usr/local/bin/awx --conf.username admin --conf.password password --conf.host http://192.168.10.10 instance_groups list -f human | grep tower
  when: "'hap1' in inventory_hostname"
  retries: 99
  delay: 10
  register: result
  until: result.rc == 0 and result.stdout != ''

- name: Get instance host
  shell: /usr/local/bin/awx --conf.username admin --conf.password password --conf.host http://192.168.10.10 instance_groups list -f yaml
  when: "'hap1' in inventory_hostname"
  register: result

- set_fact:
    myvar: "{{ result.stdout | from_yaml }}"
  when: "'hap1' in inventory_hostname"

- set_fact:
    instance_host: "{{ myvar['results'][0]['policy_instance_list'][0] }}"
  when: "'hap1' in inventory_hostname"

- name: Display instance_host
  debug:
    var: instance_host

- name: show all the hosts matching the pattern
  debug:
    msg: yes
  when: "hostvars['hap1']['instance_host'] not in inventory_hostname"

- name: Restart docker compose
  shell: cd /var/lib/awx/build_image && docker-compose restart
  register: restart
  when: "hostvars['hap1']['instance_host'] not in inventory_hostname"

- name: show all the hosts matching the pattern
  debug:
    var: restart.stderr_lines
  when: "hostvars['hap1']['instance_host'] not in inventory_hostname"
