forwarding: yes
eth:
    static:
        - name: eth1
          ipaddr: 192.168.255.1
          netmask: 255.255.255.252

routes:
    - dev: eth1
      routes:
        - route: 192.168.0.0/16
          nh: 192.168.255.2