---
- name: Provsioning LAB:29 enviroment
  hosts: all
  become: yes

  tasks:

    # General configuration

    - name: Fix locale
      lineinfile:
        path: /etc/environment
        line: "{{ item }}"
        state: present
      with_items:
        - "LANG=en_US.utf-8"
        - "LC_ALL=en_US.utf-8"

    - name: Install Percona repo
      yum:
        name: http://www.percona.com/downloads/percona-release/redhat/0.1-6/percona-release-0.1-6.noarch.rpm
        state: present

    - name: Update Percona release
      yum:
        name: percona-release
        state: latest

    - name: Install Percona
      yum:
        name: Percona-Server-server-57
        state: present




