---
- name: Consul install and configure role
  hosts: consul
  gather_facts: True
  become_user: root
  become: True

  roles:
    - consul

- name: Patroni install and configure role
  hosts: 
    - pg1
    - pg2
    - pg3
  gather_facts: True
  become_user: root
  become: True

  roles:
    - patroni

- name: Install and configure HAProxy
  hosts: haproxy
  gather_facts: True
  become_user: root
  become: True
  roles:
    - haproxy
  tags:
    - haproxy
