---
- name: restart firewall
  service:
    name: firewalld.service
    state: restarted
    enabled: yes
    
- name: restart haproxy
  service: 
    name: haproxy
    state: restarted

- name: restart keepalived
  service: 
    name: keepalived
    state: restarted
