---
- name: Install packages
  yum:
    name: '{{ yum_packages }}'
    state: present

- name: Add pg_probackup repo
  yum:
    name: http://repo.postgrespro.ru/pg_probackup/keys/pg_probackup-repo-centos.noarch.rpm
    state: present

- name: Install pg_probackup
  yum:
    name: pg_probackup-10
    state: present

- name: Add postgresql-10 repo
  yum:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present

- name: Install postgresql-10
  yum:
    name: 
      - postgresql10-server
      - postgresql10
    state: present

- name: Upgrade pip3
  pip: 
    name: pip
    executable: pip3
    state: latest

- name: Install pip3 packages
  pip:
    name: "{{ pip3_packages }}"
    state: present
    executable: pip3
  tags:
    - pip

- name: Install patroni
  pip:
    name: patroni[consul]
    state: present
    executable: pip3
  tags:
    - pip-patroni

- name: Configure patroni systemd service file
  template:
    src: patroni.service.j2
    dest: /etc/systemd/system/patroni.service

- name: Create patroni directories
  file:
    path: "{{ item }}"
    state: directory
    owner: postgres
    group: postgres
    mode: 0700
  with_items:
      - /var/data/base
      - /etc/patroni/

- name: Copy patroni config file
  template:
    src: patroni.yml.j2
    dest: /etc/patroni/patroni.yml

- name: Start patroni cluster
  systemd:
    name: patroni
    state: restarted
    daemon_reload: True
    enabled: true

- name: Create directory .ssh for postgres user
  file:
    path: /var/lib/pgsql/.ssh
    state: directory
    owner: postgres
    group: postgres
    mode: '0700'

- name: Copy SSH keys for postgres user
  template:
    src: "{{ item.src }}"
    dest: "/var/lib/pgsql/.ssh/{{ item.dest }}"
    mode: 0600
    owner: postgres
    group: postgres
  with_items:
    - { src: id_rsa, dest: id_rsa}
    - { src: id_rsa.pub, dest: id_rsa.pub}

- name: Update authorized_keys file for postgres user
  lineinfile:
    path: /var/lib/pgsql/.ssh/authorized_keys
    line: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDjVzorAbaJftV0jAk2ttfQRtzJMUniEqrdNgDWoyjbGprtfjnVhk3VGlBAiQZwO94/cHKeIz0muH4/34iQmKcGnbj3rLFGrA646WB0yOMZJFtagKIEVW6/AK/zbmlwMalT/SOwYihSJhxGo7OMiAy63/e6imh5mLu8Lt13FLq9mOqeaeIRVYrXUPMV2j+7HKu0MQRXgvCV9rsCdQ+r9IrtDq2ruygHSAVf7T5Kk29sG5nbFQsXaeNrCAiBcO6A1DEkworGgCTZaZLXkdilHxoX0gbEkq5FoIq0WvwuFHO1sp7N6ndZcyeGgWDvLPOc4vNinh7DaKsspGDUS4bkhm0Z root@host"
    owner: postgres
    group: postgres
    create: yes
    state: present

- name: Wait untill cluster is up and running
  wait_for:
    host: 192.168.10.10
    port: 5000
    delay: 10

- name: Add database user - awx
  postgresql_user:
    login_host: 192.168.10.10
    port: 5000
    login_user: postgres
    login_password: gfhjkm
    name: awx
    password: awxpass
    state: present
  when: inventory_hostname == 'pg1'
    
- name: Add database - awx
  postgresql_db:
    login_host: 192.168.10.10
    port: 5000
    login_user: postgres
    login_password: gfhjkm
    name: awx
    owner: awx
    state: present
  when: inventory_hostname == 'pg1'

