---
- name: Install packages
  yum:
    name: '{{ yum_packages }}'
    state: present

- name: Add postgresql-10 repo
  yum:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present

- name: Install postgresql-10
  yum:
    name: 
      - postgresql10-server
      - postgresql10
    state: present

- name: Upgrade pip3
  pip: 
    name: pip
    executable: pip3
    state: latest

- name: Install pip3 packages
  pip:
    name: "{{ pip3_packages }}"
    state: present
    executable: pip3
  tags:
    - pip

- name: Install patroni
  pip:
    name: patroni[consul]
    state: present
    executable: pip3
  tags:
    - pip-patroni

- name: Configure patroni systemd service file
  template:
    src: patroni.service.j2
    dest: /etc/systemd/system/patroni.service

- name: Create patroni directories
  file:
    path: "{{ item }}"
    state: directory
    owner: postgres
    group: postgres
    mode: 0700
  with_items:
      - /var/data/base
      - /etc/patroni/

- name: Copy patroni config file
  template:
    src: patroni.yml.j2
    dest: /etc/patroni/patroni.yml

- name: Start patroni cluster
  systemd:
    name: patroni
    state: restarted
    daemon_reload: True
    enabled: true

- name: Wait untill cluster is up and running
  wait_for:
    host: 192.168.10.10
    port: 5000
    delay: 10

- name: Add database user - awx
  postgresql_user:
    login_host: 192.168.10.10
    port: 5000
    login_user: postgres
    login_password: gfhjkm
    name: awx
    password: awxpass
    state: present
  when: inventory_hostname == 'pg1'
    
- name: Add database - awx
  postgresql_db:
    login_host: 192.168.10.10
    port: 5000
    login_user: postgres
    login_password: gfhjkm
    name: awx
    owner: awx
    state: present
  when: inventory_hostname == 'pg1'


