---
yum_packages:
    - unzip
    - ansible 
    - git 
    - gcc 
    - gcc-c++ 
    - nodejs 
    - gettext 
    - device-mapper-persistent-data 
    - lvm2 
    - bzip2 
    - python-pip 
    - python-devel 
    - docker-ce

pip_packages:
    - docker-compose
    