---
- name: Common configuration
  hosts: all
  gather_facts: True
  become: True

  roles:
    - common

- name: Proxy configuration
  hosts: proxy
  gather_facts: True
  become: True

  roles:
    - haproxy

- name: DCS configuration
  hosts: mon
  gather_facts: True
  become: True

  roles:
    - consul

- name: Patroni configuration
  hosts: db
  gather_facts: True
  become: True

  roles:
    - patroni

- name: AWX configuration
  hosts: task, proxy
  gather_facts: True
  become: True

  roles:
    - awx-nodes
