---
- name: Common configuration
  hosts: all
  gather_facts: yes
  become: yes
  tags:
    - common
  roles:
    - common
    - node_exporter

- name: Monotoring servers configuration
  hosts: mon
  gather_facts: no
  become: yes
  tags:
    - monitor
  roles:
    - prometheus
    - grafana

- name: Journal server configuration
  hosts: mon
  gather_facts: no
  become: yes
  tags:
    - log
  roles:
    - journal_server

- name: Webjournal configuration
  hosts: mon
  gather_facts: no
  become: yes
  tags:
    - log
  roles:
    - webjournal

- name: Journal client configuration
  hosts: all
  gather_facts: no
  become: yes
  tags:
    - log
  roles:
    - journal_client

- name: Proxy deploy
  hosts: proxy
  gather_facts: yes
  become: yes
  roles:
    - haproxy

- name: Consul deploy
  hosts: mon
  gather_facts: yes
  become: yes
  roles:
    - consul

- name: Patroni deploy
  hosts: db
  gather_facts: yes
  become: yes
  tags: 
    - db
  roles:
    - patroni

- name: Backup deploy
  hosts: mon
  gather_facts: no
  become: yes
  tags: 
    - db
  roles:
    - pg_probackup

- name: AWX deploy
  hosts: awx_instance_group_web, awx_instance_group_task
  become: yes
  become_method: sudo
  max_fail_percentage: 0
  tags:
    - awx
  roles:
    - rabbitmq_cluster
    - awx_ha
