---
- name: Common configuration
  hosts: all
  gather_facts: yes
  become: yes

  roles:
    - common

- name: Proxy deploy
  hosts: proxy
  gather_facts: yes
  become: yes

  roles:
    - haproxy

- name: Consul deploy
  hosts: mon
  gather_facts: yes
  become: yes

  roles:
    - consul

- name: Patroni deploy
  hosts: db
  gather_facts: yes
  become: yes

  roles:
    - patroni

- name: AWX deploy
  hosts: awx_instance_group_web, awx_instance_group_task
  become: yes
  become_method: sudo
  max_fail_percentage: 0

  roles:
    - rabbitmq_cluster
    - awx_ha
