# -*- mode: ruby -*-
# vim: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "srv" do |box|
    box.vm.box = "centos/7"
    box.vm.hostname = "srv"
    
    #box.vm.network :private_network, ip: "192.168.51.100"
    box.vm.network :forwarded_port, guest: 22, host: 62801, id: "ssh"
    box.vm.network :forwarded_port, guest: 8080, host: 8080
    box.vm.network :forwarded_port, guest: 8081, host: 8081
    box.vm.network :forwarded_port, guest: 8082, host: 8082
    box.vm.network :forwarded_port, guest: 8083, host: 8083

    box.vm.box_check_update = false

    box.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "8096"]
      vb.customize ["modifyvm", :id, "--cpus", "8"]
    end

    box.vm.provision "shell", inline: <<-SHELL
      
      # install ssh keys
      #mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
      #sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
      #systemctl restart sshd
      # correct locale
      #echo "LANG=en_US.utf-8" > /etc/environment
      #echo "LC_ALL=en_US.utf-8" > /etc/environment
      # enable EPEL
      #yum install -y epel-release
      # install basic packages
      #yum install -y bash-completion vim-enhanced mc setools-console
                    
      SHELL

    box.vm.provision "ansible" do |ansible|
        ansible.compatibility_mode = "2.0"
        ansible.playbook = "provision.yml"
        ansible.verbose = "false"
        ansible.become = "true"
        ansible.limit = "all"
    end

  end

end
