# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :lab14 => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.150'
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "200"]
          end
          
          box.vm.provision "shell", inline: <<-SHELL
            mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
            sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
            systemctl restart sshd
            # enable EPEL
            #yum install epel-release -y
            # install basic packages
            #yum install -y bash-completion bash-completion-extras vim-enhanced mc setools-console
            useradd user_admin
            useradd user_noadmin
            echo "Otus2019" | passwd --stdin user_admin
            echo "Otus2019" | passwd --stdin user_noadmin
            groupadd admin
            gpasswd -a user_admin admin
            gpasswd -a vagrant admin
            cp /vagrant/usr/local/bin/check_login.sh /usr/local/bin/check_login.sh
            chmod +x /usr/local/bin/check_login.sh
            cp /vagrant/etc/pam.d/sshd /etc/pam.d/sshd
                    
          SHELL

      end
  end
end
