forwarding: yes
eth:
    static:
        - name: eth1
          ipaddr: 10.1.3.1
          netmask: 255.255.255.0
        - name: eth2
          ipaddr: 10.1.2.1
          netmask: 255.255.255.0
        - name: eth3
          ipaddr: 172.16.1.1
          netmask: 255.255.255.0
ospf_asym:
    router_id: 1.1.1.1
    interfaces:
        - name: eth1
          cost: 10
        - name: eth2
          cost: 100
        - name: eth3
          cost: 10

traceroute: 172.16.2.2
