forwarding: yes
eth:
    static:
        - name: eth1
          ipaddr: 10.2.3.2
          netmask: 255.255.255.0
        - name: eth2
          ipaddr: 10.1.2.2
          netmask: 255.255.255.0
        - name: eth3
          ipaddr: 172.16.2.2
          netmask: 255.255.255.0

ospf:
    router_id: 2.2.2.2
    interfaces:
        - name: eth1
          cost: 10
        - name: eth2
          cost: 10
        - name: eth3
          cost: 10

ospf_sym:
    router_id: 2.2.2.2
    interfaces:
        - name: eth1
          cost: 10
        - name: eth2
          cost: 100
        - name: eth3
          cost: 10

traceroute: 172.16.1.1