forwarding: yes
eth:
    static:
        - name: eth1
          ipaddr: 10.1.3.3
          netmask: 255.255.255.0
        - name: eth2
          ipaddr: 10.2.3.3
          netmask: 255.255.255.0

ospf_asym:
    router_id: 3.3.3.3
    interfaces:
        - name: eth1
          cost: 10
        - name: eth2
          cost: 10

ospf_sym:
    router_id: 2.2.2.2
    interfaces:
        - name: eth1
          cost: 10
        - name: eth2
          cost: 100
        - name: eth3
          cost: 10