---
- name: restart firewall
  service:
    name: firewalld.service
    state: restarted
    enabled: yes
    
- name: nginx restart
  systemd:
    name: nginx
    state: restarted

- name: webjournal restart
  systemd:
    name: webjournal
    state: restarted
    daemon_reload: yes