# Provsioning LAB:20 enviroment
---
- name: Provsioning LAB:20 enviroment
  hosts: all
  become: yes

  tasks:

    - name: Install needed network manager libs
      package:
        name:
          - NetworkManager-glib
          - nm-connection-editor
          - libsemanage-python
          - policycoreutils-python
        state: present

    - name: Enable IPv4 forwarding on the routers
      sysctl:
        name: net.ipv4.conf.all.forwarding
        value: '1'
        state: present
      when: "'Router' in inventory_hostname"

    - name: Configure Team interfaces
      shell: "nmcli connection add type team con-name {{ item.conn_name}} ifname {{ item.conn_name }} team.runner lacp team.runner-fast-rate yes ipv4.method {{ item.ipv4_method }} {% if item.ipv4_method != 'disabled' %} ipv4.addresses {{ item.ipv4_addresses }} {% endif %} ipv6.method {{ item.ipv6_method }}"
      with_items: 
        - '{{ teams }}'
      when: teams is defined

    - name: Configure members of Team interfaces
      shell: "nmcli connection add type ethernet con-name {{ item.conn_name }} ifname {{ item.ifname }} master {{ item.master }}"
      with_items: 
        - '{{ team_members }}'
      when: team_members is defined

    - name: Configure eth interfaces
      shell: "nmcli connection add type ethernet con-name {{ item.conn_name}} ifname {{ item.ifname }} ipv4.method {{ item.ipv4_method }} {% if item.ipv4_method != 'disabled' %} ipv4.addresses {{ item.ipv4_addresses }} {% endif %} ipv6.method {{ item.ipv6_method }}"
      with_items: 
        - '{{ eths }}'
      when: eths is defined

    - name: Configure Vlan sub-interfaces
      shell: "nmcli connection add type vlan con-name {{ item.conn_name }} vlan.id {{ item.vlan_id }} vlan.parent {{ item.vlan_parent }} ipv4.method {{ item.ipv4_method }} {% if item.ipv4_method != 'disabled' %} ipv4.addresses {{ item.ipv4_addresses }} {% endif %} ipv6.method {{ item.ipv6_method }}"
      with_items: 
        - '{{ vlans }}'
      when: vlans is defined

    - name: Remove default from eth0
      shell: nmcli connection modify System\ eth0 ipv4.never-default yes && nmcli connection up System\ eth0
      when: gw is defined

    - name: Setup default route
      shell: "nmcli connection modify {{ gw.conn_name }} ipv4.gateway {{ gw.ip4 }} && nmcli connection up {{ gw.conn_name }}"
      when: gw is defined

