# -*- mode: ruby -*-
# vim: set ft=ruby :
# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
:inetRouter => {
        :box_name => "centos/7",
        #:public => {:ip => '192.168.11.100', :adapter => 1},
        :fwd => {:guest => 22, :host => 62001},
        :net => [
                   {adapter: 2, virtualbox__intnet: "router-net-1"},
                   {adapter: 3, virtualbox__intnet: "router-net-2"},
                ]
  },
  :centralRouter => {
        :box_name => "centos/7",
        :fwd => {:guest => 22, :host => 62002},
        :net => [
                   {adapter: 2, virtualbox__intnet: "router-net-1"},
                   {adapter: 3, virtualbox__intnet: "router-net-2"},
                   {adapter: 4, virtualbox__intnet: "vsw1"},
                ]
  },  
  :testServer1 => {
        :box_name => "centos/7",
        :fwd => {:guest => 22, :host => 62003},
        :net => [
                   {adapter: 2, virtualbox__intnet: "vsw1"},
                ]
  },  
  :testClient1 => {
        :box_name => "centos/7",
        :fwd => {:guest => 22, :host => 62004},
        :net => [
                   {adapter: 2, virtualbox__intnet: "vsw1"},
                ]
  },  
  :testServer2 => {
        :box_name => "centos/7",
        :fwd => {:guest => 22, :host => 62005},
        :net => [
                   {adapter: 2, virtualbox__intnet: "vsw1"},
                ]
  },  
  :testClient2 => {
        :box_name => "centos/7",
        :fwd => {:guest => 22, :host => 62006},
        :net => [
                   {adapter: 2, virtualbox__intnet: "vsw1"},
                ]
  },  
}

Vagrant.configure("2") do |config|

    MACHINES.each do |boxname, boxconfig|

        config.vm.define boxname do |box|

            box.vm.box = boxconfig[:box_name]
            box.vm.host_name = boxname.to_s

            #boxconfig[:fwd].each do |fwdconf|
            #    box.vm.network "forwarded_port", fwdconf
            #end

            if boxconfig.key?(:fwd)
                box.vm.network "forwarded_port", boxconfig[:fwd]
            end

            boxconfig[:net].each do |ipconf|
                box.vm.network "private_network", ipconf
            end
            
            if boxconfig.key?(:public)
                box.vm.network "public_network", boxconfig[:public]
            end

            box.vm.provider :virtualbox do |vb|
                vb.customize ["modifyvm", :id, "--memory", "256"]
            end

            box.vm.provision "shell", inline: <<-SHELL
                mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
                # correct locale
                echo "LANG=en_US.utf-8" > /etc/environment
                echo "LC_ALL=en_US.utf-8" > /etc/environment
            SHELL
            
            case boxname.to_s
            when "inetRouter"
                box.vm.provision "shell", run: "always", inline: <<-SHELL
                    #sysctl net.ipv4.conf.all.forwarding=1
                    iptables -t nat -A POSTROUTING ! -d 192.168.0.0/16 -o eth0 -j MASQUERADE
                SHELL
            when "testClient2"
                box.vm.provision "ansible" do |ansible|
                    ansible.compatibility_mode = "2.0"
                    ansible.playbook = "provision.yml"
                    ansible.verbose = "true"
                    ansible.become = "true"
                    ansible.limit = "all"
                end
            end

        end

    end
  
end