---
- name: HAProxy | common | Fix locale
  lineinfile:
    path: /etc/environment
    line: "{{ item }}"
    state: present
  with_items:
    - "LANG=en_US.utf-8"
    - "LC_ALL=en_US.utf-8"

- name: HAProxy | common | Turn off SELinux
  selinux:
    state: disabled

- name: HAProxy | Ensure HAProxy is installed.
  yum:
    name: haproxy
    state: present

- name: HAProxy | Copy HAProxy configuration
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
    validate: haproxy -f %s -c -q
  notify: restart haproxy

- name: HAProxy | Ensure HAProxy is started and enabled on boot
  systemd: 
    name: haproxy
    state: started
    enabled: true
