---
- name: Provsioning LAB:21 enviroment
  hosts: all
  become: yes

  tasks:

    - name: Install EPEL
      yum:
        name: epel-release
        state: present

    - name: Install packages
      yum:
        name: '{{ item }}'
        state: present
      when: packages is defined
      loop: '{{ packages }}'

    - name: Enable IPv4 forwarding on the routers
      sysctl:
        name: net.ipv4.conf.all.forwarding
        value: '1'
        state: present
      when: forwarding is defined and forwarding == True

    - name: Disable ZeroConf
      lineinfile:
        path: /etc/sysconfig/network
        line: "NOZEROCONF=yes"
        state: present

    - name: Configure IPv4 static on interfaces
      template:
        src: templates/ifcfg_static.j2
        dest: "/etc/sysconfig/network-scripts/ifcfg-{{ item.name }}"
        owner: root
        group: root
        mode: 0644
      when: eth.static is defined
      with_items:
        - '{{ eth.static }}'
      notify: reload eth static

    - name: Configure IPv4 DHCP on interfaces
      template:
        src: templates/ifcfg_dhcp.j2
        dest: "/etc/sysconfig/network-scripts/ifcfg-{{ item.name }}"
        owner: root
        group: root
        mode: 0644
      when: eth.dhcp is defined
      with_items:
        - '{{ eth.dhcp }}'
      notify: reload eth dhcp

    - name: Configure IPv4 static routes
      template:
        src: templates/route.j2
        dest: "/etc/sysconfig/network-scripts/route-{{ item.dev }}"
        owner: root
        group: root
        mode: 0644
      when: routes is defined
      with_items:
        - '{{ routes }}'
      notify: reload static routes

    - name: Enable password auth
      lineinfile:
        path: /etc/ssh/sshd_config
        regex: "^PasswordAuthentication"
        line: PasswordAuthentication yes
        state: present
      notify: reload sshd

    - name: Copy file with owner and permissions
      copy:
        src: configs/iptables
        dest: /etc/sysconfig/iptables
        owner: root
        group: root
        mode: 0644
      when: knocking is defined and knocking == True
      notify: reload iptables

    - name: Enable services
      systemd:
        state: '{{ item.state }}'
        name: '{{ item.name }}'
        enabled: '{{ item.enabled }}'
      when: services is defined
      with_items:
        - '{{ services }}'

  handlers:

    - name: reload eth dhcp
      shell: "ifdown {{ item.name }}; ifup {{ item.name }}"
      with_items:
        - '{{ eth.dhcp }}'

    - name: reload eth static
      shell: "ifdown {{ item.name }}; ifup {{ item.name }}"
      with_items:
        - '{{ eth.static }}'

    - name: reload static routes
      shell: "ifdown {{ item.dev }}; ifup {{ item.dev }}"
      with_items:
        - '{{ routes }}'

    - name: reload sshd
      systemd:
        state: restarted
        name: sshd

    - name: reload iptables
      systemd:
        state: restarted
        name: iptables

