# -*- mode: ruby -*-
# vim: set ft=ruby :
# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
    :inetRouter => {
        :box_name => "centos/7",
        #:public => {:ip => '192.168.11.100', :adapter => 1},
        :fwd => {:guest => 22, :host => 62101},
        :net => [
                   {adapter: 2, virtualbox__intnet: "router-net"},
                ]
    },
    :inetRouter2 => {
        :box_name => "centos/7",
        :fwd => {:guest => 22, :host => 62108},
        :net => [
                   {adapter: 2, virtualbox__intnet: "inet2-crouter"},
                   {adapter: 3, ip: '192.168.51.100', netmask: "255.255.255.0"},
                ]
    },
    :centralRouter => {
        :box_name => "centos/7",
        :fwd => {:guest => 22, :host => 62102},
        :net => [
                   {adapter: 2, virtualbox__intnet: "router-net"},
                   {adapter: 3, virtualbox__intnet: "dir-net"},
                   {adapter: 4, virtualbox__intnet: "hw-net"},
                   {adapter: 5, virtualbox__intnet: "wifi-net"},
                   {adapter: 6, virtualbox__intnet: "wan1-net"},
                   {adapter: 7, virtualbox__intnet: "wan2-net"},
                   {adapter: 8, virtualbox__intnet: "inet2-crouter"},
                ]
    },  
    :centralServer => {
        :box_name => "centos/7",
        :fwd => {:guest => 22, :host => 62103},
        :net => [
                   {adapter: 2, virtualbox__intnet: "dir-net"},
                ]
    },
}

Vagrant.configure("2") do |config|

    MACHINES.each do |boxname, boxconfig|

        config.vm.define boxname do |box|

            box.vm.box = boxconfig[:box_name]
            box.vm.host_name = boxname.to_s

            #boxconfig[:fwd].each do |fwdconf|
            #    box.vm.network "forwarded_port", fwdconf
            #end

            if boxconfig.key?(:fwd)
                box.vm.network "forwarded_port", boxconfig[:fwd]
            end

            boxconfig[:net].each do |ipconf|
                box.vm.network "private_network", ipconf
            end
            
            if boxconfig.key?(:public)
                box.vm.network "public_network", boxconfig[:public]
            end

            box.vm.provider :virtualbox do |vb|
                vb.customize ["modifyvm", :id, "--memory", "256"]
            end

            box.vm.provision "shell", inline: <<-SHELL
                mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
                # correct locale
                echo "LANG=en_US.utf-8" > /etc/environment
                echo "LC_ALL=en_US.utf-8" > /etc/environment
            SHELL
            
            case boxname.to_s
            when "inetRouter"
                box.vm.provision "shell", run: "always", inline: <<-SHELL
                    iptables -t nat -A POSTROUTING ! -d 192.168.0.0/16 -o eth0 -j MASQUERADE
                SHELL

            when "centralServer"
                box.vm.provision "ansible" do |ansible|
                    ansible.compatibility_mode = "2.0"
                    ansible.playbook = "provision.yml"
                    ansible.verbose = "true"
                    ansible.become = "true"
                    ansible.limit = "all"
                end

            end
        end
    end
end