---
- name: Add the user node_exporter
  user:
    name: node_exporter
    create_home: no
    shell: /bin/false

- name: Unarchive node_exporter
  unarchive:
    src: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_expoerter_ver }}/node_exporter-{{ node_expoerter_ver }}.linux-amd64.tar.gz"
    dest: /tmp/
    copy: no

- name: Copy node_exporter
  copy:
    src: /tmp/node_exporter-{{ node_expoerter_ver }}.linux-amd64/node_exporter
    dest: /usr/local/bin/
    mode: '0755'
    remote_src: yes
    
- name: Copy systemd unit
  template:
    src: node_exporter.service
    dest: /etc/systemd/system/

- name: Start node_exporter
  systemd:
    name: node_exporter
    state: restarted
    daemon_reload: yes
    enabled: yes


