---
# tasks file for haproxy

- name: Install packages
  yum:
    name: '{{ yum_packages }}'
    state: present

- name: Enable non-local IP binding
  sysctl:
    name: '{{ item }}'
    value: '1'
    reload: yes
    state: present
  with_items:
    - 'net.ipv4.ip_nonlocal_bind'
    - 'net.ipv6.ip_nonlocal_bind'

- name: Copy KeepaliveD configuration
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  notify: restart keepalived

- name: Copy HAProxy configuration
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
    validate: haproxy -f %s -c -q
  notify: restart haproxy

- name: Ensure HAProxy is started and enabled on boot
  systemd: 
    name: haproxy
    state: started
    enabled: true