---
- name: Update the firewall rules
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  with_items: "{{ enable_port }}"
  notify: restart firewall
  tags: fw_rules

- meta: flush_handlers

- name: Install packages
  yum:
    name: '{{ yum_packages }}'
    state: present

- name: Download and unarchive Consul files
  unarchive:
    src: https://releases.hashicorp.com/consul/1.5.3/consul_1.5.3_linux_amd64.zip
    dest: /usr/sbin/
    remote_src: True

- name: Consul | Create consul user
  user:
    name: consul
    shell: /bin/false
    home: /etc/consul.d

- name: Consul | Prepare consul directories
  file:
    path: "{{ item }}"
    state: directory
    owner: consul
    group: consul
  with_items:
      - /etc/consul.d
      - /opt/consul

- name: Configure systemd service file for Consul
  template:
    src: consul.service.j2
    dest: /etc/systemd/system/consul.service

- name: Consul | Configure Consul
  template:
    src: consul.json.j2
    dest: /etc/consul.d/consul.json
    owner: consul
    group: consul
  notify:
    - restart consul

- name: Ensure Consul is started and enabled on boot
  systemd: 
    name: consul
    state: started
    enabled: true