---
- name: restart firewall
  service:
    name: firewalld.service
    state: restarted
    enabled: yes

- name: journal-remote restart
  systemd:
    name: systemd-journal-remote
    state: restarted
    daemon_reload: yes
